export const APP_PERMISSION_ROLES = {
  DASHBOARD_VIEW: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],

  COURSE_CREATE: ['ROLE_ADMINISTRADOR'],
  COURSE_EDIT: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE'],
  COURSE_DELETE: ['ROLE_ADMINISTRADOR'],
  COURSE_TOGGLE_STATUS: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE'],
  COURSE_MANAGE_PERMISSIONS: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],
  COURSE_ADD_MEMBER: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE'],
  COURSE_REMOVE_MEMBER: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE'],
  COURSE_REPORT: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO'],
  COURSE_COVER_MANAGE: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO'],

  PERSON_CREATE: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO'],
  PERSON_EDIT: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO'],
  PERSON_DELETE: ['ROLE_ADMINISTRADOR'],
  PERSON_IMPORT: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO'],
  PERSON_USER_CREATE: ['ROLE_ADMINISTRADOR'],

  USER_CREATE: ['ROLE_ADMINISTRADOR'],
  USER_EDIT: ['ROLE_ADMINISTRADOR'],
  USER_DELETE: ['ROLE_ADMINISTRADOR'],
  USER_CHANGE_PASSWORD: ['ROLE_ADMINISTRADOR'],

  UNIT_CREATE: ['ROLE_ADMINISTRADOR'],
  UNIT_EDIT: ['ROLE_ADMINISTRADOR'],
  UNIT_DELETE: ['ROLE_ADMINISTRADOR'],

  CATEGORY_MANAGE: ['ROLE_ADMINISTRADOR'],
  TIPO_CURSO_MANAGE: ['ROLE_ADMINISTRADOR'],

  ATIVIDADE_CREATE: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],
  ATIVIDADE_EDIT: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],
  ATIVIDADE_DELETE: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],
  ATIVIDADE_REPORT: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],
  ATIVIDADE_EVIDENCIA_MANAGE: ['ROLE_ADMINISTRADOR', 'ROLE_GERENTE', 'ROLE_SECRETARIO', 'ROLE_COORDENADOR_ATIVIDADE'],

  AUDIT_LOG_VIEW: ['ROLE_ADMINISTRADOR'],
  ACTION_LOG_VIEW: ['ROLE_ADMINISTRADOR']
} as const;

export type AppPermission = keyof typeof APP_PERMISSION_ROLES;
